name: Release

on:
  push:
    branches: ["main"]

env:
  GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
  PYTHONUTF8: 1

permissions:
  contents: write
  id-token: write

jobs:
  versioning:
    name: Update Version
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Run TinySemVer
        uses: ashvardanian/tinysemver@v3
        with:
          verbose: "true"
          version-file: "VERSION"
          update-version-in: |
            CITATION.cff:^version: (\d+\.\d+\.\d+)
            pyproject.toml:^version = "(\d+\.\d+\.\d+)"
            networkxternal/__init__.py:^__version__ = "(\d+\.\d+\.\d+)"
          dry-run: "false"
          push: "true"
          create-release: "true"
          github-token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  rebase:
    name: Rebase Dev Branch
    needs: versioning
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - name: Perform Rebase
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main-dev
          git rebase origin/main
      - name: Push Changes
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          branch: main-dev
          force: True

  publish:
    name: Publish to PyPI
    needs: versioning
    runs-on: ubuntu-24.04
    environment: pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
      - name: Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
